// Generated by backend/scripts/gen_frontend_types.py from app/models/.
// Do not edit: change the Pydantic model and re-run the script.

import type { PriorityCategory, PriorityLetter } from "./installs";
import type { Derived } from "./derived";

export interface WareInstall {
  id?: string;
  ware_id: string;
  rating?: number;
  grade?: string;
  wireless?: boolean;
  parent_id?: string | null;
  included?: boolean;
  side?: string | null;
  /** `<selectcyberware>`: the implant this one is keyed to (Implant Medic,
   *  Nanohive Soft). A label, like Chummer's `<extra>` — it grants nothing.
   */
  extra?: string | null;
  /** bought through the Black Market Pipeline: 10% off (Chummer's
   *  `<discountedcost>`, which the quality's categories allow)
   */
  discounted?: boolean;
}

export interface AdeptPowerInstall {
  id?: string;
  power_id: string;
  rating?: number;
  extra?: string | null;
  discounted?: boolean;
  force?: number | null;
}

export interface SpellInstall {
  id?: string;
  spell_id: string;
  force?: number | null;
  source_quality_id?: string | null;
  alchemical?: boolean;
}

export interface QiFocusInstall {
  id?: string;
  rating?: number;
  power_id: string;
  extra?: string | null;
  power_rating?: number;
}

export interface SpiritInstall {
  id?: string;
  spirit_id: string;
  force?: number;
  services?: number;
  bound?: boolean;
  hits?: number | null;
  opposed_hits?: number | null;
}

export interface ComplexFormInstall {
  id?: string;
  form_id: string;
  level?: number | null;
  extra?: string | null;
}

export interface SpriteInstall {
  id?: string;
  sprite_id: string;
  level?: number;
  services?: number;
  registered?: boolean;
  hits?: number | null;
  opposed_hits?: number | null;
}

export interface FocusInstall {
  id?: string;
  gear_id: string;
  force?: number;
  crafted?: boolean;
  formula_bought?: boolean;
  hits?: number | null;
  opposed_hits?: number | null;
  extra?: string | null;
}

export interface ArmorInstall {
  id?: string;
  armor_id: string;
  rating?: number;
  /** the price picked for a `Variable(lo-hi)` piece (Clothing) */
  cost?: number | null;
  equipped?: boolean;
  wireless?: boolean;
  /** bought through the Black Market Pipeline: 10% off (Chummer's
   *  `<discountedcost>`, which the quality's categories allow)
   */
  discounted?: boolean;
}

export interface ArmorModInstall {
  id?: string;
  mod_id: string;
  parent_id?: string | null;
  included?: boolean;
  rating?: number;
  wireless?: boolean;
  /** Custom Fit (Stack) `<selectarmor>`: the catalog name of the armor this
   *  piece was tailored to stack with (Chummer's `<extra>`)
   */
  stack_with?: string;
}

export interface WeaponInstall {
  id?: string;
  weapon_id: string;
  qty?: number;
  loaded_ammo_id?: string | null;
  /** bought through the Black Market Pipeline: 10% off (Chummer's
   *  `<discountedcost>`, which the quality's categories allow)
   */
  discounted?: boolean;
}

export interface VehicleModInstall {
  id?: string;
  mod_id: string;
  parent_id?: string | null;
  included?: boolean;
  rating?: number;
}

export interface WeaponMountInstall {
  id?: string;
  parent_id?: string | null;
  size_id?: string;
  visibility_id?: string;
  flexibility_id?: string;
  control_id?: string;
  included?: boolean;
  weapon_install_id?: string | null;
  allowedweapons?: string;
}

export interface WeaponAccessoryInstall {
  id?: string;
  accessory_id: string;
  parent_id?: string | null;
  included?: boolean;
  rating?: number;
  mount?: string;
  /** bought through the Black Market Pipeline: 10% off (Chummer's
   *  `<discountedcost>`, which the quality's categories allow)
   */
  discounted?: boolean;
}

export interface CommlinkInstall {
  id?: string;
  gear_id: string;
  rating?: number;
  /** how many alike — a stack of burner Meta Links */
  qty?: number;
  /** bought through the Black Market Pipeline: 10% off (Chummer's
   *  `<discountedcost>`, which the quality's categories allow)
   */
  discounted?: boolean;
}

export interface GearInstall {
  id?: string;
  gear_id: string;
  rating?: number;
  qty?: number;
  parent_id?: string | null;
  included?: boolean;
  capacity_override?: string | null;
  array_order?: string[];
  extra?: string | null;
  active?: boolean;
  /** the price picked for a `Variable(lo-hi)` item (a Custom Item, a
   *  Commlink App), and a Custom Item's own name
   */
  cost?: number | null;
  name?: string | null;
  /** bought through the Black Market Pipeline: 10% off (Chummer's
   *  `<discountedcost>`, which the quality's categories allow)
   */
  discounted?: boolean;
}

export interface CustomDrugPart {
  component_id: string;
  level?: number;
}

export interface CustomDrugInstall {
  id?: string;
  name?: string;
  grade?: string;
  qty?: number;
  active?: boolean;
  parts?: CustomDrugPart[];
}

export interface LifestyleInstall {
  id?: string;
  lifestyle_id: string;
  months?: number;
  /** Points bought above the lifestyle's own Comforts / Neighborhood /
   *  Security (RF p.219, Chummer's `<comforts>` / `<area>` / `<security>`).
   */
  comforts?: number;
  area?: number;
  security?: number;
  quality_ids?: string[];
  quality_extras?: Record<string, string>;
}

export interface ExoticSkillInstall {
  id?: string;
  skill_name: string;
  extra?: string;
  rating?: number;
}

export interface ContactInstall {
  id?: string;
  name?: string;
  role?: string | null;
  connection?: number;
  loyalty?: number;
  group?: boolean;
  free?: boolean;
  forced_loyalty?: number | null;
  force_group?: boolean;
  source_quality_id?: string | null;
  free_connection?: number;
  free_loyalty?: number;
}

export interface MartialArtInstall {
  id?: string;
  art_id: string;
  techniques?: string[];
  free?: boolean;
  source_quality_id?: string | null;
}

export interface InitiationChoice {
  id?: string;
  grade?: number;
  kind?: "metamagic" | "art" | string;
  option_id?: string;
  group?: boolean;
  ordeal?: boolean;
  schooling?: boolean;
}

export interface SubmersionChoice {
  id?: string;
  grade?: number;
  echo_id?: string;
  extra?: string | null;
  group?: boolean;
  ordeal?: boolean;
  schooling?: boolean;
}

export interface CharacterOptions {
  redliner_torso?: boolean;
  redliner_skull?: boolean;
}

export interface CharacterSettings {
  name?: string;
  books?: string[];
  /** Which `<prioritytable>` in `priorities.xml` the rows come from —
   *  Standard, Prime Runner, Street Level, or one custom data adds.
   */
  priority_table?: string;
  /** Every knob below is `None` when the settings file did not change it, so
   *  an unset field keeps the printed SR5 value. `app.rules.rules_for` folds
   *  them into a `Rules`; see `app/settings_file.py` for the XML side.
   */
  sum_to_ten?: number | null;
  chargen_karma?: number | null;
  karma_chargen_pool?: number | null;
  karma_attribute?: number | null;
  karma_active_skill?: number | null;
  karma_skill_group?: number | null;
  karma_knowledge?: number | null;
  karma_specialization?: number | null;
  karma_knowledge_specialization?: number | null;
  karma_spell?: number | null;
  karma_complex_form?: number | null;
  karma_enhancement?: number | null;
  karma_mystic_pp?: number | null;
  karma_martial_technique?: number | null;
  /** The first level of a skill, priced apart from the rest
   *  (`<karmanewactiveskill>` and friends; Chummer's `RangeCost`).
   */
  karma_new_active_skill?: number | null;
  karma_new_knowledge_skill?: number | null;
  karma_new_skill_group?: number | null;
  /** Karma per point of Force to bond a focus, by kind
   *  (`<karmaweaponfocus>` and friends; Chummer's `Focus.BindingKarmaCost`).
   */
  karma_alchemical_focus?: number | null;
  karma_banishing_focus?: number | null;
  karma_binding_focus?: number | null;
  karma_centering_focus?: number | null;
  karma_counterspelling_focus?: number | null;
  karma_disenchanting_focus?: number | null;
  karma_flexible_signature_focus?: number | null;
  karma_masking_focus?: number | null;
  karma_power_focus?: number | null;
  karma_qi_focus?: number | null;
  karma_ritual_spellcasting_focus?: number | null;
  karma_spell_shaping_focus?: number | null;
  karma_spellcasting_focus?: number | null;
  karma_summoning_focus?: number | null;
  karma_sustaining_focus?: number | null;
  karma_weapon_focus?: number | null;
  karma_initiation_flat?: number | null;
  karma_initiation_per_grade?: number | null;
  karma_submersion_flat?: number | null;
  karma_submersion_per_grade?: number | null;
  quality_karma_limit?: number | null;
  chargen_skill_max?: number | null;
  chargen_knowledge_skill_max?: number | null;
  chargen_attributes_at_max?: number | null;
  career_skill_max?: number | null;
  career_knowledge_skill_max?: number | null;
  chargen_avail_max?: number | null;
  min_initiative_dice?: number | null;
  max_initiative_dice?: number | null;
  min_coldsim_initiative_dice?: number | null;
  max_coldsim_initiative_dice?: number | null;
  min_hotsim_initiative_dice?: number | null;
  max_hotsim_initiative_dice?: number | null;
  min_astral_initiative_dice?: number | null;
  max_astral_initiative_dice?: number | null;
  /** `<limbcount>` / `<excludelimbslot>`: how many limbs a cyberlimb's
   *  STR / AGI is averaged across, and a slot left out of that average
   */
  limb_count?: number | null;
  exclude_limb_slot?: string | null;
  karma_to_nuyen?: number | null;
  priority_karma_nuyen_base?: number | null;
  /** `<contactpointsexpression>`'s multiplier: free contact points are
   *  unaugmented CHA times this (3 in Standard, 6 in Prime Runner).
   */
  contact_free_mult?: number | null;
  /** `<exceednegativequalities>`: negative qualities may pass the karma
   *  limit at chargen; `<exceednegativequalitiesnobonus>`: the part past it
   *  gives no karma.
   */
  exceed_negative_qualities?: boolean | null;
  exceed_negative_qualities_no_bonus?: boolean | null;
  /** `<exceedpositivequalities>`: positive qualities may pass the limit. */
  exceed_positive_qualities?: boolean | null;
  /** `<dontdoublequalities>` / `<dontdoublequalityrefunds>` */
  dont_double_quality_purchases?: boolean | null;
  dont_double_quality_refunds?: boolean | null;
  /** `<usecalculatedpublicawareness>` */
  use_calculated_public_awareness?: boolean | null;
  /** `<noarmorencumbrance>` / `<uncappedarmoraccessorybonuses>` */
  no_armor_encumbrance?: boolean | null;
  uncapped_armor_accessory_bonuses?: boolean | null;
  /** `<esslossreducesmaximumonly>` / `<donotroundessenceinternally>` */
  ess_loss_reduces_maximum_only?: boolean | null;
  dont_round_essence_internally?: boolean | null;
  /** `<multiplyrestrictedcost>` / `<restrictedcostmultiplier>` and the
   *  forbidden pair: what an R / F item bought in career costs, times.
   */
  multiply_restricted_cost?: boolean | null;
  restricted_cost_multiplier?: number | null;
  multiply_forbidden_cost?: boolean | null;
  forbidden_cost_multiplier?: number | null;
  /** `<allowinitiationincreatemode>` */
  allow_initiation_in_create_mode?: boolean | null;
  /** `<cyberlegmovement>`: two cyberlegs set the AGI movement runs off */
  cyberleg_movement?: boolean | null;
  /** `<allowpointbuyspecializationsonkarmaskills>` */
  allow_point_buy_specializations_on_karma_skills?: boolean | null;
  /** The attribute capping bound spirits / registered sprites
   *  (`<boundspiritexpression>` / `<registeredspriteexpression>`).
   */
  bound_spirit_attr?: string | null;
  registered_sprite_attr?: string | null;
  banned_ware_grades?: string[];
  /** `<customdatadirectorynames>`, enabled ones only, in the order the file
   *  gave them — order decides who wins when two directories edit the same
   *  entry, so it is not sorted.
   */
  customdata?: string[];
  /** Content hash of the custom-data files this character was built against.
   *  The client sends the files once and this token thereafter; see
   *  `app/customdata.py`.
   */
  dataset?: string;
  /** Tags the file changed away from Chummer's Standard that this app does
   *  not implement. Surfaced as a warning rather than swallowed — a house
   *  rule silently dropped is worse than one the sheet says it ignored.
   */
  unsupported?: string[];
}

export interface CareerBaseline {
  attributes?: Record<string, number>;
  skills?: Record<string, number>;
  skill_groups?: Record<string, number>;
  knowledge_skills?: Record<string, number>;
  skill_specializations?: string[];
  exotic_skills?: Record<string, number>;
  /** None for a baseline saved before qualities were recorded: those
   *  characters keep the chargen price for every quality they hold.
   */
  quality_ids?: string[] | null;
  /** Every gear / ware instance id owned on entering career, so what was
   *  bought after is known (Restricted / Forbidden markup). None for an
   *  older baseline: nothing is marked up.
   */
  item_ids?: string[] | null;
}

export interface RewardEntry {
  id?: string;
  label?: string;
  karma?: number;
  nuyen?: number;
}

export interface Character {
  id: string;
  name: string;
  build_method?: "Priority" | "SumToTen" | "Karma" | string;
  priorities: Record<PriorityCategory, PriorityLetter>;
  metatype: string;
  metavariant?: string | null;
  talent: string;
  attributes: Record<string, number>;
  /** Priority / Sum-to-Ten creation: of `attributes[key]`, how many of the
   *  top levels were bought with karma rather than attribute points
   *  (Chummer's `<karma>` beside `<base>`). Ignored by a Karma build, where
   *  every level is karma anyway.
   */
  attribute_karma?: Record<string, number>;
  skills: Record<string, number>;
  /** The same split for skills: of `skills[name]` / `knowledge_skills[name]`,
   *  the top levels bought with karma rather than skill / knowledge points.
   */
  skill_karma?: Record<string, number>;
  knowledge_karma?: Record<string, number>;
  skill_groups: Record<string, number>;
  /** of `skill_groups[name]`, the top levels bought with karma */
  skill_group_karma?: Record<string, number>;
  skill_specializations?: Record<string, string>;
  exotic_skills?: ExoticSkillInstall[];
  knowledge_skills: Record<string, number>;
  native_languages?: string[];
  knowledge_categories?: Record<string, string>;
  quality_ids: string[];
  quality_extras?: Record<string, string>;
  cyberware?: WareInstall[];
  bioware?: WareInstall[];
  skill_picks?: Record<string, string>;
  adept_powers?: AdeptPowerInstall[];
  mystic_pp?: number;
  mentor_id?: string | null;
  mentor_choices?: string[];
  mentor_extras?: Record<string, string>;
  adept_enhancements?: string[];
  qi_foci?: QiFocusInstall[];
  spells?: SpellInstall[];
  spirits?: SpiritInstall[];
  complex_forms?: ComplexFormInstall[];
  sprites?: SpriteInstall[];
  foci?: FocusInstall[];
  armor?: ArmorInstall[];
  armor_mods?: ArmorModInstall[];
  weapons?: WeaponInstall[];
  weapon_accessories?: WeaponAccessoryInstall[];
  commlinks?: CommlinkInstall[];
  cyberdecks?: GearInstall[];
  rccs?: GearInstall[];
  optics?: GearInstall[];
  programs?: GearInstall[];
  apps?: GearInstall[];
  sensors?: GearInstall[];
  drones?: GearInstall[];
  vehicles?: GearInstall[];
  gear?: GearInstall[];
  custom_drugs?: CustomDrugInstall[];
  vehicle_mods?: VehicleModInstall[];
  weapon_mounts?: WeaponMountInstall[];
  lifestyles?: LifestyleInstall[];
  contacts?: ContactInstall[];
  martial_arts?: MartialArtInstall[];
  initiate_grade?: number;
  initiations?: InitiationChoice[];
  submersion_grade?: number;
  submersions?: SubmersionChoice[];
  karma_nuyen?: number;
  notes?: string;
  age?: string;
  sex?: string;
  height?: string;
  weight?: string;
  eyes?: string;
  hair?: string;
  skin?: string;
  appearance?: string;
  background?: string;
  concept?: string;
  portrait?: string;
  career?: boolean;
  karma_earned?: number;
  nuyen_earned?: number;
  /** a Chummer career save's balance less what this app works out from
   *  the build and the rewards: spending the app does not model (rent,
   *  purchases at their own prices). Added to what is left, either sign.
   */
  karma_adjust?: number;
  nuyen_adjust?: number;
  career_baseline?: CareerBaseline | null;
  street_cred?: number;
  /** SR5 p.373: two points burned take a point of Notoriety off */
  burnt_street_cred?: number;
  notoriety_bonus?: number;
  /** Public Awareness the GM has awarded — Chummer's `<publicawareness>`,
   *  a counter it stores as told rather than works out.
   */
  public_awareness?: number;
  reward_log?: RewardEntry[];
  /** what a Chummer save's expense log spent (negative), kept as history:
   *  the balance itself is already met by `karma_adjust` / `nuyen_adjust`,
   *  so these rows are shown and written back, never counted again
   */
  expense_log?: RewardEntry[];
  tradition_id?: string | null;
  stream_id?: string | null;
  options?: CharacterOptions;
  settings?: CharacterSettings;
  /** Output of compute(); kept dict[str, Any] here (Pydantic-friendly, no
   *  round-trip validation). Its real shape is engine.compute.derived_types.DerivedDict.
   */
  derived: Derived;
}
