"""Rows bought as gear: ware, armor, weapons, vehicles, commlinks, gear, drugs, lifestyles."""

from __future__ import annotations

import uuid
from typing import Literal

from pydantic import BaseModel, Field


class CyberwareInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    ware_id: str
    #: Selected ammunition for the weapon generated by this implant.
    loaded_ammo_id: str | None = None
    rating: int = 1
    grade: str = "Standard"
    wireless: bool = True
    parent_id: str | None = None
    included: bool = False
    side: str | None = None
    # `<selectcyberware>`: the implant this one is keyed to (Implant Medic,
    # Nanohive Soft). A label, like Chummer's `<extra>` — it grants nothing.
    extra: str | None = None
    #: the price picked for a `Variable(lo-hi)` piece (Biosculpting)
    cost: int | None = None
    #: bought through the Black Market Pipeline: 10% off (Chummer's
    #: `<discountedcost>`, which the quality's categories allow)
    discounted: bool = False
    #: `<essdiscount>`: a percentage off this piece's essence, as the GM
    #: allows under `<allowcyberwareessdiscounts>` (Chummer's `ESSDiscount`,
    #: -100 to 100; negative costs more)
    ess_discount: int = Field(default=0, ge=-100, le=100)


class ArmorInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    armor_id: str
    rating: int = 1
    #: the price picked for a `Variable(lo-hi)` piece (Clothing)
    cost: int | None = None
    equipped: bool = True
    wireless: bool = True
    #: bought through the Black Market Pipeline: 10% off (Chummer's
    #: `<discountedcost>`, which the quality's categories allow)
    discounted: bool = False


class ArmorModInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    mod_id: str
    parent_id: str | None = None
    included: bool = False
    rating: int = 1
    wireless: bool = True
    # Custom Fit (Stack) `<selectarmor>`: the catalog name of the armor this
    # piece was tailored to stack with (Chummer's `<extra>`)
    stack_with: str = ""


class WeaponInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    weapon_id: str
    qty: int = 1
    loaded_ammo_id: str | None = None
    #: comes with a drone's own entry: free, and not the player's to remove
    included: bool = False
    #: bought through the Black Market Pipeline: 10% off (Chummer's
    #: `<discountedcost>`, which the quality's categories allow)
    discounted: bool = False


class VehicleModInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    mod_id: str
    parent_id: str | None = None
    included: bool = False
    rating: int = 1


class WeaponMountInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    parent_id: str | None = None
    size_id: str = ""
    visibility_id: str = ""
    flexibility_id: str = ""
    control_id: str = ""
    included: bool = False
    weapon_install_id: str | None = None
    allowedweapons: str = ""


class WeaponAccessoryInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    accessory_id: str
    parent_id: str | None = None
    included: bool = False
    rating: int = 1
    mount: str = ""
    #: bought through the Black Market Pipeline: 10% off (Chummer's
    #: `<discountedcost>`, which the quality's categories allow)
    discounted: bool = False


class CommlinkInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    gear_id: str
    rating: int = 1
    #: how many alike — a stack of burner Meta Links
    qty: int = Field(default=1, ge=1, le=999)
    #: bought through the Black Market Pipeline: 10% off (Chummer's
    #: `<discountedcost>`, which the quality's categories allow)
    discounted: bool = False


class GearInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    gear_id: str
    rating: int = 1
    qty: int = 1
    parent_id: str | None = None
    included: bool = False
    capacity_override: str | None = None
    array_order: list[str] = Field(default_factory=list)
    extra: str | None = None
    active: bool = False  # drugs/toxins: effect currently applied
    # Cyberdeck programs only; missing on old saves means the former all-running
    # behavior. Purchase/move UI explicitly stops new programs. RCC rules differ.
    running: bool = True
    # Imported Electronic Parts can be fractional packs. None means qty sales
    # lots; a value records acquired quarter-packs per parent, before consumption.
    purchased_parts_units: int | None = Field(default=None, ge=0, le=100000)
    # Cyberdeck modules only; this is not generic gear equipment management.
    equipped: bool = True
    #: the price picked for a `Variable(lo-hi)` item (a Custom Item, a
    #: Commlink App), and a Custom Item's own name
    cost: int | None = None
    name: str | None = Field(default=None, max_length=200)
    #: bought through the Black Market Pipeline: 10% off (Chummer's
    #: `<discountedcost>`, which the quality's categories allow)
    discounted: bool = False


class CustomDrugPart(BaseModel):
    """One component in a mixed drug, at the level it was added at."""

    component_id: str
    level: int = 0


class CustomDrugInstall(BaseModel):
    """A drug the character cooked rather than bought (CF p.190).

    It has no catalog entry — the parts are the drug — so unlike every other
    piece of gear it carries its own name.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    grade: str = "Standard"
    qty: int = 1
    active: bool = False  # effect currently applied, like GearInstall.active
    parts: list[CustomDrugPart] = Field(default_factory=list)


class LifestyleInstall(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    lifestyle_id: str
    months: int = 1
    #: Points bought above the lifestyle's own Comforts / Neighborhood /
    #: Security (RF p.219, Chummer's `<comforts>` / `<area>` / `<security>`).
    comforts: int = 0
    area: int = 0
    security: int = 0
    quality_ids: list[str] = Field(default_factory=list)
    quality_extras: dict[str, str] = Field(default_factory=dict)


class ElectronicPartsSupply(BaseModel):
    """Explicit acquisition; quantities are quarter-packs, never currency."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    kind: Literal["salvaged", "equipment", "gm"] = "salvaged"
    units: int = Field(ge=1, le=100000)
    note: str = Field(default="", max_length=500)
    equipment_id: str | None = None


class ElectronicPartsAllocation(BaseModel):
    source_id: str
    units: int = Field(ge=1, le=100000)


class ElectronicModificationRecord(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    modification_id: str
    host_id: str
    gear_id: str
    status: Literal["pending", "completed", "historical", "cancelled"] = "pending"
    required_units: int = Field(default=0, ge=0, le=100000)
    allocations: list[ElectronicPartsAllocation] = Field(default_factory=list, max_length=100)
    # Backend freezes these values when construction is confirmed. Later
    # array/quality edits cannot consume or refund parts.
    host_snapshot: dict[str, int] = Field(default_factory=dict, max_length=10)
    rule_version: Literal[1] = 1
    note: str = Field(default="", max_length=500)
