"""Run & Gun entries checked against the official Japanese edition (Phase 5).

Unlike the other curated modules, this one is mostly a *verification* record.
Of the 483 RG-sourced catalog entries, 430 already render in Japanese from the
upstream community `ja-jp_data.xml`; nobody had checked them against a published
translation. So an entry appearing in `RG` below means "a human read this term in
the Japanese Run & Gun and this is what it says" — whether or not it agrees with
what upstream already had. Pinning the agreeing ones too is the point: the
overlay outranks the vendored XML, so a later `CHUMMER_REF` bump cannot quietly
change a term somebody verified.

Scope is the same names-only boundary the overlay has always had: entry names
and category names, never rules text, tables or headings.

`RG_UNVERIFIED` is the other half of the ledger — RG names deliberately left on
English fallback, because the Japanese edition has no entry for them or the term
was too uncertain to pin. Together the two must cover every RG name in the
catalog; `tests/test_rg_coverage.py` enforces that, and tracks how far the pass
has got.

Generated by `scripts/import_rg_worksheet.py` from a filled-in worksheet — see
`scripts/make_rg_worksheet.py` and docs/plans/translation-plan.md phase 5. Edit
through the worksheet rather than by hand, so the two halves stay in step.
"""

from __future__ import annotations

# english name -> official Japanese, as printed in the Japanese Run & Gun
RG: dict[str, str] = {}

# RG names deliberately left on English fallback (no official term / not pinned)
RG_UNVERIFIED: tuple[str, ...] = ()
