"""Street Grimoire entries checked against the Shadowrun Codex (Phase 5).

Street Grimoire has no Japanese edition. What it has is the *Shadowrun Codex*, a
Japanese compendium that reprints much of its content — so this table is a
record of "a human found this term in the Codex and this is what it says",
and the Codex's own index is how a term is found: the page numbers Chummer
stores are the English book's and do not locate anything here.

Of the 465 SG-sourced catalog entries, 334 already render in Japanese from the
upstream community `ja-jp_data.xml` — 131 do not. So the worksheet's "="
shorthand, which carried the Run & Gun pass (see `scripts/ja_curated_rg.py`),
answers about two thirds of this book, and the remaining third has to be typed
in from the Codex.

Scope is the same names-only boundary the overlay has always had: entry names
and category names, never rules text, tables or headings.

`SG_UNVERIFIED` is the other half of the ledger — names deliberately left on
English fallback, because the Codex has no entry for them or the term was too
uncertain to pin. `tests/test_book_coverage.py` keeps the two halves from
overlapping and pins how far the pass has got.

Generated by `scripts/import_ja_worksheet.py --book SG` from a filled-in
worksheet — see `scripts/make_ja_worksheet.py` and
docs/plans/translation-plan.md phase 5. Edit through the worksheet rather than
by hand, so the two halves stay in step.
"""

from __future__ import annotations

# english name -> official Japanese, as printed in the Shadowrun Codex
SG: dict[str, str] = {}

# SG names deliberately left on English fallback (no official term / not pinned)
SG_UNVERIFIED: tuple[str, ...] = ()
