"""Run Faster entries checked against the Shadowrun Codex (Phase 5).

Run Faster has no Japanese edition. What it has is the *Shadowrun Codex*, a
Japanese compendium that reprints much of its content — so this table is a
record of "a human found this term in the Codex and this is what it says",
and the Codex's own index is how a term is found: the page numbers Chummer
stores are the English book's and do not locate anything here.

Of the 732 RF-sourced catalog entries, 91 already render in Japanese from the
upstream community `ja-jp_data.xml` — 641 do not. Where Run & Gun arrived
almost fully translated and needed checking (see `scripts/ja_curated_rg.py`),
this book is the other case: the worksheet's "=" shorthand can answer barely an
eighth of it, and the rest has to be typed in from the Codex.

Scope is the same names-only boundary the overlay has always had: entry names
and category names, never rules text, tables or headings.

`RF_UNVERIFIED` is the other half of the ledger — names deliberately left on
English fallback, because the Codex has no entry for them or the term was too
uncertain to pin. `tests/test_book_coverage.py` keeps the two halves from
overlapping and pins how far the pass has got.

Generated by `scripts/import_ja_worksheet.py --book RF` from a filled-in
worksheet — see `scripts/make_ja_worksheet.py` and
docs/plans/translation-plan.md phase 5. Edit through the worksheet rather than
by hand, so the two halves stay in step.
"""

from __future__ import annotations

# english name -> official Japanese, as printed in the Shadowrun Codex
RF: dict[str, str] = {}

# RF names deliberately left on English fallback (no official term / not pinned)
RF_UNVERIFIED: tuple[str, ...] = ()
