"""Run & Gun entries checked against the official Japanese edition (Phase 5).

Unlike the other curated modules, this one is mostly a *verification* record.
Of the 483 RG-sourced catalog entries, 430 already render in Japanese from the
upstream community `ja-jp_data.xml`; nobody had checked them against a published
translation. So an entry appearing in `RG` below means "a human read this term in
the Japanese Run & Gun and this is what it says" — whether or not it agrees with
what upstream already had. Pinning the agreeing ones too is the point: the
overlay outranks the vendored XML, so a later `CHUMMER_REF` bump cannot quietly
change a term somebody verified.

Scope is the same names-only boundary the overlay has always had: entry names
and category names, never rules text, tables or headings.

`RG_UNVERIFIED` is the other half of the ledger — RG names deliberately left on
English fallback, because the Japanese edition has no entry for them or the term
was too uncertain to pin. Together the two must cover every RG name in the
catalog; `tests/test_rg_coverage.py` enforces that, and tracks how far the pass
has got.

Generated by `scripts/import_rg_worksheet.py` from a filled-in worksheet — see
`scripts/make_rg_worksheet.py` and docs/plans/translation-plan.md phase 5. Edit
through the worksheet rather than by hand, so the two halves stay in step.
"""

from __future__ import annotations

# english name -> official Japanese, as printed in the Japanese Run & Gun
RG: dict[str, str] = {
    # --- armor -------------------------------------------------------------
    "Social": "社交",
    # --- armor+armor_mods --------------------------------------------------
    "Custom Fit": "カスタムフィット",
    "Custom Fit (Stack)": "カスタムフィット(累積)",
    "Gear Access": "装備アクセス",
    "Newest Model": "最新モデル",
    "Padded": "急所保護",
    "Radiation Shielding": "放射線遮蔽",
    "Restrictive": "動きにくい",
    "Ruthenium Polymer Coating": "ルテニウム・ポリマー・コーティング",
    # --- armor_mods --------------------------------------------------------
    "Auto-Injector": "自動注射器",
    "Fresnel Fabric": "フレネル布",
    "Gel Packs": "ゲルパック",
    "Illuminating": "発光",
    "Nightshade IR and Contacts": "ナイトシェードIRとコンタクト",
    "Pulse Weave": "パルス・ウィーブ",
    "Rapid Transit: Diamond": "ラピッド・トランジット：ダイヤモンド",
    "Rapid Transit: Elite": "ラピッド・トランジット：エリート",
    "Rapid Transit: Platinum": "ラピッド・トランジット：プラチナ",
    "Responsive Interface Gear: Armor": "レスポンシブ・インターフェース・ギア(RIG)：アーマー",
    "Responsive Interface Gear: Helmet": "レスポンシブ・インターフェース・ギア(RIG)：ヘルメット",
    "Shock Weave": "ショック・ウィーブ",
    "Universal Mirror Material": "自在反射材",
    "YNT Softweave Armor": "YNT ソフトウィーブ・アーマー",
    # --- category ----------------------------------------------------------
    "High-Fashion Armor Clothing": "高級ファッション志向のアーマー・クロージング",
    "Nightshade IR": "ナイトシェード IR",
    "Specialty Armor": "専用の防具",
    # --- weapon_accessories ------------------------------------------------
    "Collapsed Frame": "折り畳み式",
    "Gecko Grip (for Weapon with No Stock Slot)": "ゲッコー・グリップ(ストック・スロットを持たない武器用)",
    "Silencer (PSK-3 Collapsible Heavy Pistol)": "消音器(PSK-3 折り畳み式ヘビーピストル)",
    "Vindicator 200-Round Belt": "ヴィンディケーター 200(ベルト)",
    # --- weapons -----------------------------------------------------------
    "Chainsaw": "チェーンソー",
    "SA Retiarius Net Gun": "SA レティアルス・ネットガン",
}

# RG names deliberately left on English fallback (no official term / not pinned)
RG_UNVERIFIED: tuple[str, ...] = (
    "AK-98",
    "FN MAG-5",
    "HK XM30",
)
