"""Hand translations for the smaller entity buckets still on English fallback
(Phase 2b, see docs/translation-plan.md): mentors, lifestyles, martial arts,
adept powers, echoes, complex forms.

House style matches what upstream already translated:
  * meanings for concept words (強打, 反射強化), katakana for proper names
  * parenthetical mentor variants "(Alt)" / "(SHB)" are left on English fallback,
    the same as the upstream file does.

Consumed by import_ja_from_refs.py; every key is checked against catalog() by
tests/test_translation_overrides.py.
"""

from __future__ import annotations

ENTITIES: dict[str, str] = {
    # --- mentor spirits (skip the "(Alt)/(SHB)" parenthetical variants) --------
    "The Adversary": "敵対者",
    "Planar Entity": "次元界の存在",
    "Holy Text": "聖典",
    "Tohu Wa-Bohu": "トフ・ワ・ボフ",
    "Heinzelmännchen": "ハインツェルメンヒェン",
    "Capricorn": "カプリコーン",
    "Mystic Guardian": "神秘の守護者",
    # --- lifestyles (meaning-based, cf. 街 / 不法居住 / 中流) --------------------
    "Commercial": "商業施設",
    "Bolt Hole": "隠れ家",
    "Traveler": "旅暮らし",
    # --- martial arts (transliteration, cf. アルニス・デ・マーノ) ---------------
    "Way of Unified Mana (Hapsum-Do)": "統一マナの道（ハプスムドー）",
    "Alpine Wrestling": "アルパイン・レスリング",
    "German Jujitsu": "ジャーマン柔術",
    "Esdo": "エスド",
    "Urban Brawl Parkour": "アーバンブロウル・パルクール",
    "Sternschutz Tactical": "シュテルンシュッツ・タクティカル",
    "Arbeitskreis INI": "アルバイツクライスINI",
    "Circle Fencing": "サークル・フェンシング",
    "Kreussler Fencing": "クロイスラー・フェンシング",
    "Asthenologica": "アステノロジカ",
    # --- adept powers (meaning-based, cf. 反射強化 / 危険関知) ------------------
    "Improved Potential (Chaos Mentor)": "潜在力強化：(混沌メンター)",
    "Berserker's Rage": "狂戦士の怒り",
    "Elemental Body": "元素の身体",
    "Elemental Weapon": "元素の武器",
    "Hang Time": "滞空",
    "Keratin Control": "ケラチン制御",
    "Kinesics Mastery": "キネシクス習熟",
    "Plague Cloud": "疫病の雲",
    "Rapid Draw": "早抜き",
    "Riposte": "リポスト",
    "Skate": "滑走",
    "Spirit Claw": "精霊の爪",
    "Spirit Ram": "精霊の衝角",
    "Stillness": "静止",
    "Toxic Strike": "毒撃",
    "Feign Illness": "仮病",
    "Feign Death": "擬死",
    "Transmit Damage": "ダメージ転送",
    "Light Touch": "軽い手",
    "Mimic": "模倣",
    "Demara": "ディマラ",
    "Heightened Concentration": "集中力向上",
    "Indomitable Will": "不屈の意志",
    "Maintain Warmth": "保温",
    "Memory Displacement": "記憶転移",
    "Power Swimming": "高速水泳",
    "Power Swimming (Elf or Troll)": "高速水泳（エルフ／トロール）",
    "Rooting": "根付き",
    "Supernatural Toughness": "超常の頑健さ",
    "Adept Spell": "アデプト呪文",
    "Adept Accident": "アデプト・アクシデント",
    "Focused Archery": "集中射法",
    "Kiai": "気合",
    "Master Archer": "弓術の達人",
    "Precision Throwing": "精密投擲",
    "Body Sculpt": "肉体成形",
    "Lie Detector": "嘘発見",
    "Osmosis": "浸透",
    "Ventriloquism": "腹話術",
    "Mystic Aptitude": "神秘の適性",
    "State of Purity": "清浄なる境地",
    "Berserker Temper": "狂戦士の気質",
    # --- echoes (technomancer; katakana / 共振〜, cf. 共振リンク) ---------------
    "Fight or Flight Filter": "闘争逃走フィルター",
    "Mathemagics": "マスマジック",
    "Quiet": "クワイエット",
    "Resonance Riding": "共振ライディング",
    "Resonance Scream": "共振スクリーム",
    "Sleepwalker": "スリープウォーカー",
    "Contaminate": "コンタミネート",
    "Siphon": "サイフォン",
    "Pryon": "プライオン",
    "Defrag": "デフラグ",
    "Aegis": "イージス",
    "Draining Spike": "ドレイン・スパイク",
    "Neural Synergy": "ニューラル・シナジー",
    "Predictive Analytics": "予測分析",
    "Resonance Resistance": "共振抵抗",
    "The Van der Waals Effect": "ファンデルワールス効果",
    "Will of the Resonance": "共振の意志",
    "Sourcerer Daemon": "ソーサラー・デーモン",
    # --- complex forms (katakana / meaning, cf. パルス・ストーム) --------------
    "Derezz": "デレズ",
    "IC Tray": "ICトレイ",
    "Redundancy": "冗長化",
    "Misread Marks": "マーク誤読",
    "Coriolis": "コリオリ",
    "Overdrive": "オーバードライブ",
    "Hyperthreading": "ハイパースレッディング",
    "Sprite Pet": "スプライト・ペット",
    "Causal Nexus": "因果連結",
    "Dissonance Spike": "ディソナンス・スパイク",
    "Forced Heuristics": "強制ヒューリスティクス",
    "Arc Feedback": "アーク・フィードバック",
    "Bootleg Program": "海賊版プログラム",
    "Host Emulator": "ホスト・エミュレータ",
    "Mirrored Persona": "ミラー・ペルソナ",
    "Pinch": "ピンチ",
    "Primed Charge": "プライム・チャージ",
    "Resonance Bind": "共振バインド",
    "Resonance Cache": "共振キャッシュ",
    "Search History": "検索履歴",
    "Weaken Data Bomb": "データボム弱体化",
    "Weaken Encryption": "暗号化弱体化",
}
