from __future__ import annotations

from ..data_loader import (  # noqa: F401  (engine re-export barrel)
    CHARGEN_AVAIL_MAX,
    CHARGEN_DEVICE_RATING_MAX,
    CHARGEN_WARE_ATTR_BONUS_MAX,
    PHYSICAL_ATTRS,
    catalog,
    eval_formula,
)
from ..improvements import (  # noqa: F401  (engine re-export barrel)
    ATTR_ALIASES,
    apply_bonus_nodes,
    collect_effects,
    compact_limit_modifiers,
    special_armor_totals,
    substitute_rating,
)
from ..models import (  # noqa: F401  (engine re-export barrel)
    ArmorInstall,
    CareerBaseline,
    CharacterState,
    CommlinkInstall,
    RewardEntry,
    WeaponInstall,
)
from .compute import (  # noqa: F401  (engine re-export barrel)
    _effective_attr_spec,
    career_raise_karma,
    compute,
    default_attributes,
    nuyen_spend_breakdown,
    resolve_attribute_selects,
    resolve_gear,
    resolve_movement,
    snapshot_career_baseline,
    sync_reward_totals,
)
from .constants import (  # noqa: F401  (engine re-export barrel)
    ADEPT_TALENTS,
    BLACK_MARKET_AVAIL_BONUS,
    BUILD_METHOD_KARMA,
    CAREER_SKILL_GROUP_MAX,
    CAREER_SKILL_MAX,
    COMPLEX_FORM_TALENTS,
    FOCUS_TALENTS,
    KARMA_ACTIVE_SKILL,
    KARMA_ATTRIBUTE,
    KARMA_CHARGEN_POOL,
    KARMA_KNOWLEDGE,
    KARMA_NUYEN_MAX,
    KARMA_SKILL_GROUP,
    KARMA_SPECIALIZATION,
    KARMA_TO_NUYEN,
    MAG_TALENTS,
    MARTIAL_ART_CHARGEN_STYLE_MAX,
    MARTIAL_ART_CHARGEN_TECHNIQUE_MAX,
    MENTOR_SPIRIT_ID,
    MYSTIC_PP_KARMA,
    NEGATIVE_QUALITY_KARMA_CAP,
    NUYEN_CHARGEN_KEEP_MAX,
    PRIORITY_KARMA_NUYEN_BASE,
    RES_TALENTS,
    SPELL_TALENTS,
    SPIRIT_TALENTS,
    SPRITE_TALENTS,
    SUM_TO_TEN_BUDGET,
    SUM_TO_TEN_COST,
    TRUST_FUND_STIPEND,
    _normalize_side,
    quality_addspirit_extra_key,  # noqa: F401  (re-exported for tests)
    quality_contact_extra_key,
    quality_spirit_category_extra_key,
)
from .contacts import (  # noqa: F401  (contact network + Ex-Con / Erased caps)
    apply_erased_lifestyle_cap,
    apply_excon_ware_ban,
    resolve_contacts,
    sync_quality_contacts,
)
from .formulas import (  # noqa: F401  (stat-expression helpers)
    _add_leading_int,
    _ceil_div,
    _replace_leading_int,
    parse_armor_value,
)
from .gear import (  # noqa: F401  (gear pipeline clusters; see engine/gear/)
    _append_gear_weapons,
    _append_ware_weapons,
    _apply_recoil_totals,
    _clamp_rating,
    _ensure_drone_equipment,
    _public_weapon,
    _publish_drone_stats,
    _recompute_worn_armor,
    _resolve_apps,
    _resolve_armor_mods,
    _resolve_drones,
    _resolve_matrix_devices,
    _resolve_misc_gear,
    _resolve_optics,
    _resolve_programs,
    _resolve_sensors,
    _resolve_vehicle_mods,
    _resolve_weapon_accessories,
    _resolve_weapon_mounts,
    apply_active_drugs,
    apply_lifestyle_cost_mod,
    apply_reach_bonus,
    apply_smartlink_accuracy,
    apply_unarmed_bonuses,
    apply_weapon_category_dice,
    apply_weapon_category_dv,
    apply_weapon_skill_accuracy,
    bind_weapon_category_dv,
    bind_weapon_skill_accuracy,
    resolve_lifestyles,
)
from .karma import (  # noqa: F401  (cost maths)
    _active_karma_mults,
    _filter_karma_rules,
    _group_floor_map,
    _karma_cost_with_category_mods,
    _karma_raise_cost,
    _matching_karma_rules,
    _point_cost,
    _skill_category_map,
    _skill_group_category_map,
    _skill_groups_for_category,
    attribute_karma_cost,
    knowledge_excess_karma,
    knowledge_points_spent,
    skill_karma_cost,
)
from .limits import (  # noqa: F401  (chargen avail / device-rating / ware-attr caps)
    _avail_entries,
    _check_avail_limit,
    _check_device_rating_limit,
    _check_ware_attribute_cap,
    _device_rating_entries,
    _finalize_avail_tree,
    _ware_attribute_bonuses,
)
from .lookups import (  # noqa: F401  (catalog single-row accessors; see engine/lookups.py)
    _item_by_id,
    _tradition_by_id,
    find_metatype,  # noqa: F401  (re-exported for characters.py / chummer_export.py / tests)
)
from .magic import (  # noqa: F401  (awakened/emerged pipeline clusters; see engine/magic/)
    apply_focus_limits,
    apply_free_metamagics,
    apply_granted_spells,
    apply_tradition_bonuses,
    attach_focus_tests,
    attach_spirit_tests,
    attach_weapon_focus_dice,
    bind_extra_spirits,
    bind_spell_category_drain_damage,
    bind_spell_spirit_limits,
    resolve_adept_powers,
    resolve_enhancements,
    resolve_foci,
    resolve_initiation,
    resolve_mentor,
    resolve_qi_foci,
    resolve_spells,
    resolve_spirits,
    resolve_submersion,
    spell_cast_info,
    spell_defense_pools,
    spell_drain_value,  # noqa: F401  (re-exported for tests)
    spell_karma_cost,
    tradition_resist,  # noqa: F401  (re-exported for tests)
)
from .martial_arts import (  # noqa: F401  (style/technique resolution)
    resolve_martial_arts,
    sync_quality_martial_arts,
)
from .pricing import (  # noqa: F401  (post-resolve cost/avail adjustments)
    apply_black_market_avail,
    apply_overclocker,
    apply_purchase_discounts,
    apply_ware_essence_multipliers,
)
from .priority import (  # noqa: F401  (re-exported for characters.py / catalog_view.py)
    all_talent_options,
    heritage_options,
    normalize_build_method,
    priorities_are_unique,
    priority_letter_cost,
    priority_value,
    resolve_talent,
    resolve_talent_for_method,
    sum_to_ten_spent,
    talent_options,
    talent_special,
    validate_priorities,
)
from .qualities import (  # noqa: F401  (quality gather / extra-pick / binder pipeline; see engine/qualities.py)
    _quality_has_selectside,
    apply_quality_rules,
    bind_action_dice_pools,
    bind_select_powers,
    free_powers_from_grants,
    gather_qualities,
    is_way_quality,  # noqa: F401  (re-exported for characters.py / catalog_view.py)
    quality_needs_extra,
    quality_requirement_context,
    resolve_quality_sides,
    sanitize_quality_ids,  # noqa: F401  (re-exported for characters.py / catalog_view.py)
)
from .resonance import (  # noqa: F401  (technomancer pipeline; see engine/resonance.py)
    _cyberadept_res_penalty_reduction,
    apply_granted_echoes,
    attach_complex_form_tests,
    attach_sprite_tests,
    living_persona,
    resolve_complex_forms,
    resolve_sprites,
)
from .selects import (  # noqa: F401  (select-node option enumeration)
    gear_extra_options,  # noqa: F401  (re-exported for characters.py / catalog_view.py)
    selectskill_options,  # noqa: F401  (re-exported for tests)
)
from .skills import (  # noqa: F401  (knowledge / specialization / exotic / skillsoft resolution)
    _attach_skillsoft_knowledge,
    _attach_specializations,
    _copy_exotic_skill_bonuses,
    _merge_skill_ratings,
    apply_select_expertise,
    resolve_exotic_skills,
    resolve_knowledge,
    resolve_skill_mods,
    resolve_skill_picks,
    resolve_skillsofts,
    resolve_specializations,
)
from .ware import (  # noqa: F401  (cyberware/bioware pipeline clusters; see engine/ware/)
    _attach_ware_to_vehicle_mods,
    _clamp_ware_grades,
    _drop_invalid_vehicle_ware,
    _installed_ware_names,
    _public_installed,
    _required_warnings,
    _side_conflicts,
    _vehicle_hosted_ware_ids,
    _vehicle_mod_hosts,
    _zero_vehicle_hosted_essence,
    apply_cyberseeker,
    ensure_subsystems,
    limb_attribute_replace,
    redliner_incompat_warnings,
    resolve_ware,
    ware_ranges,
)
